steps:
  - name: gcr.io/cloud-builders/docker@sha256:661e95acd923514f71f47ce7b390e06a8d31b15febecf772e506babf62960528
    args:
      - build
      - --pull
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
